---
title: "Example radar plot"
author: "Jose Luis Rodriguez Gil"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: cosmo
    highlight: tango
    number_sections: true
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading the packages and formating

```{r packages, include=FALSE}

library(tidyverse)
library(janitor)
library(here)
library(lubridate) 
library(viridis)
library(scales)
library(ggradar)

```

```{r}
theme_set(theme_bw()) 
```


# Mock-up data 

```{r}

behavioural_data <- tibble(
  treatment = rep(c("No Oil - Plants", "Oil - Plants", "Oil - No plants"), each = 3),
  distance_moved = c(650, 620, 670, 500, 490, 510, 450, 420, 470),
  avg_speed = c(0.86, 0.87, 0.89, 0.75, 0.77, 0.74, 0.66, 0.65, 0.62),
  avg_acceleration = c(3.57, 3.42, 3.60, 2.67, 2.86, 2.57, 1.92, 1.67, 1.67),
  active_percentage_time = c(32, 35, 34, 25, 26, 24, 14, 13, 12)
)
  
behavioural_data

```


# First we can try making iit ourselves

We need a custom function to be able to join the oints with stratight lines

```{r}

coord_straightpolar <- function(theta = 'x', start = 0, direction = 1, clip = "on") {
  theta <- match.arg(theta, c("x", "y"))
  r <- if (theta == "x") 
    "y"
  else "x"
  ggproto(NULL, CoordPolar, theta = theta, r = r, start = start,
          direction = sign(direction), clip = clip,
          # This is the different bit
          is_linear = function(){TRUE})
}

```


Then we just make a plot and connect then make it a circle with our custom function


```{r}

behavioural_data %>% 
  mutate_at(vars(-treatment), rescale) %>% 
  pivot_longer(cols = -treatment, names_to = "endpoint", values_to = "value") %>% 
  group_by(treatment, endpoint) %>% 
  summarise(mean_value = mean(value)) %>% 
  ungroup() %>% 
  ggplot() +
  geom_point(aes(x = endpoint, y = mean_value, colour = treatment)) +
  geom_polygon(aes(x = endpoint, y = mean_value, group = treatment, colour = treatment, fill = treatment), alpha = 0.2) +
  scale_y_log10(limits = c(0.1, NA)) +
  coord_straightpolar(theta = 'x')




```

# ggradar

Prefered option, although limited in some of the formating

```{r}

behavioural_plot_ggradar <- behavioural_data %>% 
  mutate_at(vars(-treatment), rescale) %>% 
  pivot_longer(cols = -treatment, names_to = "endpoint", values_to = "value") %>% 
  group_by(treatment, endpoint) %>% 
  summarise(mean_value = mean(value)) %>% 
  ungroup() %>% 
  pivot_wider(id_cols = treatment, names_from = endpoint, values_from = mean_value) %>% 
    rename(
    'Scaled percent actie' = active_percentage_time,
    'Scaled distance moved' = distance_moved,
    'Scaled average speed' = avg_speed,
    "Scaled average acceleration" = avg_acceleration
  ) %>% 
  ggradar(plot.extent.x.sf = 2.5,
          gridline.mid.colour = "grey",
          grid.label.size = 4,
          group.line.width = 0.75,
          group.point.size = 3,
          legend.position = "bottom",
          background.circle.colour = NA,
          group.colours = c("#00AFBB", "#E7B800", "#FC4E07"),
          fill = TRUE,
          fill.alpha = 0.09,
          grid.max = 1.2) 

behavioural_plot_ggradar


```

```{r}
ggsave(here("figures", "behavioural_plot_ggradar.pdf"), behavioural_plot_ggradar,  width = 190, height = 140, units = "mm")

```





